title: KPI Reporter
description: >-
  KPI Reporter is a developer-friendly, highly customizable tool for sending
  periodic reports for the metrics that matter for your team or project.
url: https://kpireporter.com
documentation_url: https://kpi-reporter.readthedocs.io/
google_analytics: G-4X2NX02VHJ
header_pages:
  - about.md
  - pricing.md
  - blog.md
social_links:
  github: kpireporter

assets:
  sources:
    - _sass

author:
  name: KPI Reporter LLC
  email: help@kpireporter.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
