source "https://rubygems.org"

gem "jekyll", "~> 4.1.0"
gem "minima", github: "jekyll/minima"

group :jekyll_plugins do
  gem "jekyll-assets"
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
